"use strict";
let names = [];
names.push(1, 3, 77);
console.log(names);
console.log("Start of something new!");
console.log("progress!");
console.log("test: 1.01");
let ourTouple;
ourTouple = [20, false, "textIsWritten"];
console.log(ourTouple);
console.log(`the age was ${ourTouple[0]}, the text was ${ourTouple[1]}, but it read like this: ${ourTouple[2]}`);
